name: Build and Release

on:
  release:
    types: [published]  # срабатывает, когда ты создаёшь новый релиз

jobs:
  build:
    name: Build Electron App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: false

      - name: Install dependencies
        run: npm install

      - name: Generate icons (optional)
        run: npm run generate-icons || echo "No icons to generate"

      - name: Build app
        run: |
          npm run build

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.AppImage
            dist/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
